### PR TITLE
Rename set

### PR DESCRIPTION
**Pull request by light-matters**
Addresses #11 

Based on the fix-tests branch (which lives up to it's name).
Some functions have been (re)added temporarily pending discussion, test updates and resolution.

Check that this won't break your current work (it probably will) before merging. The only thing you should need to do to fix your current work is to use `update` instead of `set`.

### CODE REVIEW

**Comment by vukics** [comment]
`set` => `update` is OK, as we discussed, but I’m not sure we should base that on the `fix-tests` branch.

I wouldn’t want things like `wait` resurrected in the main branch. As we discussed, `wait` is dangerous, and anyway superseded by `anchor`.

I’m sorry for the old unit tests, but we should reverse our thinking: the present implementation of the experimental timeline in experiment.py & diagnostics.py should be considered reference.

Unit tests can be derived from those implementations.

**Comment by vukics** [comment]
OK, let’s discuss this next week. I agree that anchor is very invasive as it is now. And again, I’m sorry for being so drastic moving forward.

But as a general rule, I think we should keep things simple and close to the earth, even maybe at the cost of sacrificing some of the generality. I have the experience (from C++QED) that people in our field don’t like to use very complicated stuff when it comes to software.

**Comment by light-matters** [comment]
Apology accepted. 

I agree that simple is good, so I support the purge of obsolete things (before 1.0). I'm just (overly?) cautious about narrowing the scope too much. I reckon that between us the result will be good! It's definitely worth paying attention to your C++QED experience. My take on these things is that the docs should point people to the simplest, most obvious way of doing things and that anything 'complicated' should be optional: present, but waiting in the shadows for the complicated problems. My feeling is that scientists won't read the code anyways unless they really have to, so they won't be tripped up by extra functions that they didn't know about.

I will separate the pull request for now.

**Comment by light-matters** [comment]
I have removed `wait` and `ramp0` for now so that we can merge.

**Pull request merged**
